CREATE TABLE [dbo].[Cities]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Cities PRIMARY KEY, 
	[Name] VARCHAR(50) NULL,
	[Code] VARCHAR(50) NULL,
	[ISOCode] VARCHAR(50) NULL,
	[StatesID] [int] CONSTRAINT FK_CitiesStates FOREIGN KEY REFERENCES States(ID),
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
