CREATE TABLE [dbo].[PostsTypes]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PostsTypes PRIMARY KEY, 
	[PType] VARCHAR (255) NOT NULL CONSTRAINT UC_PostsTypes UNIQUE (PType),
	[Description]     VARCHAR (255) NULL,
	[Status] [int] NOT NULL DEFAULT 0,
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
