CREATE TABLE [dbo].[States]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_States PRIMARY KEY, 
	[Name] VARCHAR(50) NULL,
	[Code] VARCHAR(50) NULL,
	[ISOCode] VARCHAR(50) NULL,
	[CountriesID] [int] CONSTRAINT FK_StatesCountries FOREIGN KEY REFERENCES Countries(ID),
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
