CREATE TABLE [dbo].[ZipCodes]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZipCodes PRIMARY KEY, 
	[Name] VARCHAR(50) NULL,
	[Code] VARCHAR(50) NULL,
	[ISOCode] VARCHAR(50) NULL,
	[Date] [Date] NOT NULL DEFAULT GETDATE(),
	[CitiesID] [int] CONSTRAINT FK_ZipCodesCities FOREIGN KEY REFERENCES Cities(ID)
)
