CREATE TABLE [dbo].[ZipCodes]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZipCodes PRIMARY KEY, 
	[Name] VARCHAR(50) NULL,
	[Code] VARCHAR(50) NULL,
	[ISOCode] VARCHAR(50) NULL,
	[CitiesID] [int] CONSTRAINT FK_ZipCodesCities FOREIGN KEY REFERENCES Cities(ID),
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
