CREATE TABLE [dbo].[ApproverTypesUsers]
(
	[ID] INT IDENTITY(1,1) NOT NULL  CONSTRAINT PK_ApproverTypesUsers PRIMARY KEY, 
	[UsersID]  INT NOT NULL DEFAULT 1 CONSTRAINT FK_UsersApproverTypesUsers FOREIGN KEY REFERENCES Users(ID),
	[ApproverTypesID]  INT NOT NULL DEFAULT 0 CONSTRAINT FK_ApproverTypes FOREIGN KEY REFERENCES ApproverTypes(ID),
	[PostCategoriesID] INT NULL DEFAULT NULL CONSTRAINT FK_PostCategories FOREIGN KEY REFERENCES PostsCategories(ID),
	[Status] [int] NOT NULL DEFAULT 0,
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
