CREATE TABLE [dbo].[GroupsRoles]
(
	[ID] INT IDENTITY(1,1) NOT NULL  CONSTRAINT PK_GroupsRoles PRIMARY KEY, 
	[GroupsID] INT CONSTRAINT FK_GroupsRolesGroups FOREIGN KEY REFERENCES Groups(ID), 
	[RolesID] INT CONSTRAINT FK_GroupsRolesRoles FOREIGN KEY REFERENCES Roles(ID),
	[Status] [int] NOT NULL DEFAULT 0,
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
