CREATE TABLE [dbo].[UsersGroups]
(
	[ID] INT IDENTITY(1,1) NOT NULL  CONSTRAINT PK_UsersGroups PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(150) NULL,
	[UsersID] INT CONSTRAINT FK_UsersGroupsUsers FOREIGN KEY REFERENCES Users(ID),
	[GroupsID] INT CONSTRAINT FK_UsersGroupsGroups FOREIGN KEY REFERENCES Groups(ID),
	[Status] [int] NOT NULL DEFAULT 0,
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
