CREATE TABLE [dbo].[UserGroups]
(
	[ID] INT IDENTITY(1,1) NOT NULL  CONSTRAINT PK_UserGroups PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(50) NULL,
	[UsersID] INT CONSTRAINT FK_UserGroupsUsers FOREIGN KEY REFERENCES Users(ID),
	[GroupsID] INT CONSTRAINT FK_UserGroupsGroups FOREIGN KEY REFERENCES Groups(ID),
	[Status] [int] NOT NULL DEFAULT 0,
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
