CREATE TABLE [dbo].[Users]
(
	[ID] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Users PRIMARY KEY, 
    [FirstName] VARCHAR(50) NULL, 
    [LastName] VARCHAR(50) NULL, 
    [UserName] VARCHAR(50) NULL,
	[DisplayName] VARCHAR(50) NULL,
	[IsWebUser] bit NOT NULL DEFAULT 1,
	[Date]  DATETIME NOT NULL DEFAULT GETDATE(),
	[Timestamp] ROWVERSION  NOT NULL,
)
